### ISSUE TITLE
Caffe building error with conda, python 3.6 on ubuntu 16.04

### ISSUE THREAD

**Issue by moofin2017** [crowsonkb/style_transfer#16]
I am unable to build Caffe, I get a build error with conda (tried anaconda and miniconda), python 3.6 on ubuntu 16.04.

I tried the installation from the docker/ directory (This is for Ubuntu 14.04) as well as from https://github.com/BVLC/caffe/wiki/Ubuntu-16.04-or-15.10-Installation-Guide. (This is for Python 3.5 not Python 3.6 via Conda)

The error  I get is:
> //usr/lib/libgdal.so.1: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char, unsigned long) const@GLIBCXX_3.4.21'
> collect2: error: ld returned 1 exit status
> Makefile:633: recipe for target '.build_release/examples/cifar10/convert_cifar_data.bin' failed
> make: *** [.build_release/examples/cifar10/convert_cifar_data.bin] Error 1

On a side note, I am able to build with Python3.5 with ATLAS, OpenBLAS, and MKL support.

**Comment by moofin2017** [comment]
Got conda, python 3.6 working with MKL on ubuntu 16.04 using default OpenCV instead of OpenCV3. Seems 3.6 with MKL is 5-10% faster than 3.5 with MKL.
